### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by evelynDickinson** [BBS-Lab/nova-file-manager#39]
First of all, thank you both for developing and maintaining a really great package.

I have a few feature requests around permissions;

1) Limit / Jail to a directory on a specific storage so that users can navigate down but not out
2) Set the default view to list
3) Set a closure to evaluate disabling the New Folder, and Upload Feature
4) Set a closure to evaluate disabling the Rename, and Delete Folder Feature
5) Set a closure to evaluate disabling the Rename, and Delete File Feature

Thank you!

**Comment by crezra** [comment]
Hi 👋  thank you for your kind words
And yes, we will definitely be looking at implementing some of these cool ideas and will consider shipping a couple in the upcoming release.

Cheers !

**Comment by evelynDickinson** [comment]
Sweet. Thank you!

Best,

Evie
-------











Evelyn Dickinson

she/her


Founder & Technical Sorceress

Logical Alternative, inc.


(360) 774 - 0409 <1-360-774-0409>
***@***.***
https://logalt.net

**Comment by crezra** [comment]
Hi again 👋

We have added some new features to allow more access control over the file manager, you can check the documentation over here https://bbs-lab.github.io/nova-file-manager/access-control.html

Please do let us know if you're still encountering issues or if you have any other feature requests.

Regards
