### ISSUE TITLE
Unable to select a different asset without manually unselecting the current one first

### ISSUE THREAD

**Issue by milewski** [BBS-Lab/nova-file-manager#40]
As seen in the video below, It's impossible to select a different asset without unselecting the previous one first

https://user-images.githubusercontent.com/2874967/187357081-829dfc32-ddbd-4640-aa4b-ec789d2c6e9e.mov

**Comment by milewski** [comment]
I think the UX is correct if you have a `limit > 1` but when the `limit = 1` it feels wrong... and if you change the folder or navigate to page 5 for example... the modal remembers where you were at and you can't find where is the file anymore to deselect it... I will try to record another video demonstrating it tomorrow, cheers.

**Comment by milewski** [comment]
Look at this video for example... imagine that there are thousands of images uploaded... and I need to change it to another image... it will be nearly impossible to navigate between all the pages .. look into N folders and folders of folders that might have been created to find the original image just to "unselect" it to be able to select something else...

https://user-images.githubusercontent.com/2874967/187650968-a1697413-9306-4b16-ae15-8f324b02d6b9.mp4

**Comment by crezra** [comment]
Hi 👋 
This behavior was updated in the latest release, we have implemented a new system to handle selection, and added a new button to clear the selection

However, the selection is uncorrelated from the limit, means that if you have a `limit=1` and you open up the browser, that same selection will persist, and any new selection, however the submit button will be disabled.

You must clear the selection through the newly added button to reset the selection for your current field.

This decision was made with future features in mind where we will need a multi selection behavior for bulk action

Thank you for your feedback as always 👍
