### ISSUE TITLE
Add ability to upload multiple files at once

### ISSUE THREAD

**Issue by milewski** [BBS-Lab/nova-file-manager#42]
2 Features here:

1 - Would be nice if we could simply drag the asset straight into the modal window without entering the upload mode
2 - Add the ability to upload multiple assets at once, currently it only allows to upload 1 by 1

https://user-images.githubusercontent.com/2874967/187361783-466f4c9c-3c18-4784-8f9b-592b76045d53.mp4

**Comment by crezra** [comment]
Thank you for your feedback

new features were added to v0.3.0 please update and let us know if everything works as intended ! ✨
