### ISSUE TITLE
Several usability issues

### ISSUE THREAD

**Issue by milewski** [BBS-Lab/nova-file-manager#5]
Hi guys, thanks for this package it looks super clean, however I found several issues which render it unusable atm:

1 - The file selection modal is not letting me pick more than 1 image

```php
FileManager::make('Images', 'content->images')->mutliple(4),
```

2 - Having multiple FileManager on the same resource conflicts with each other, for example when selecting a `cover`, somehow it also changes the `Images`

```php
FileManager::make('Cover', 'content->cover'),
FileManager::make('Images', 'content->images')->mutliple(4),
```

3 - Although the UI is pretty nice, the `backdrop-filter` used to blur the background is super heavy which makes opening the image selection picker very laggy (tried on M1 / iMac 5k Retina), would be good if there was a setting to disable it 

4 - Scroll locking issue: https://github.com/BBS-Lab/nova-file-manager/issues/4

5 - When switching the display mode from `grid view` to `list view` clicking on any image from the list won't do anything... I was only able to select images from the grid view

6 - Impossible to make a field nullable if set any other rule to it, somehow the field always complains it is required. It works with the default nova File field 

```php
FileManager::make('glTF', 'content->gltf')->rules('nullable', 'mimes:json,gltf,glb'),
```

**Comment by mikaelpopowicz** [comment]
Hi @milewski 

Thank you for the report. We'll keep you in touch.

**Comment by mikaelpopowicz** [comment]
Hi @milewski 

1, 2, 4, 5 and 6 were fixed, you may try the latest release.

**Comment by crezra** [comment]
Thank you for your detailed feedback.
The aforementioned issues should be fixed in the newest release. 

Please feel free to reopen a new issue if you're still encountering problems.

Cheers
