### ISSUE TITLE
Disks are being modified globally through all fields on the page when saving resource

### ISSUE THREAD

**Issue by milewski** [BBS-Lab/nova-file-manager#55]
Another bug:

If you have multiple file fields and you toggle the disk selection when you hit save all fields will update the disk to the selected one..

https://user-images.githubusercontent.com/2874967/188362792-107b9f60-b9d1-40ac-a49d-6c027bbc56b4.mp4

> The image not displaying on the `private` disk was tracked here: https://github.com/BBS-Lab/nova-file-manager/issues/54

**Comment by crezra** [comment]
Hi again 👋

We have changed how the tool and field behaves when using cross-disk assets, now the disk is saved alongside the file path which allows better and more robust resolving when selecting multiple assets from different disks.

This will be included in the next release.

Thank you for reporting this

All the best
