### ISSUE TITLE
Access Controls from Menu Item

### ISSUE THREAD

**Issue by evelynDickinson** [BBS-Lab/nova-file-manager#61]
Hi there.

Amazing work on the new Access controls features! 

I'm wondering if there is any way to utilize the Show/Hide buttons methods right from the Menu Item call?

MenuSection::make('File Manager')->path('/nova-file-manager')

I'm using this primarily as a read-only file browser/download for one of my projects. 

Thank you!

**Comment by crezra** [comment]
Hi !

Unfortunately this is out of the scope of the package, I would recommend checking out Laravel Nova's documentation on how to handle this use case.

All the best
