### ISSUE TITLE
Nested Menu Item Path Inoperative

### ISSUE THREAD

**Issue by evelynDickinson** [BBS-Lab/nova-file-manager#62]
I'm getting a 404 with an s3 disk with the path:

MenuItem::make('File Manager')->path('/nova-file-manager/feed-archive')

My workaround is:

MenuItem::link('Feed Archive', '/nova-file-manager?path=%2Ffeed-archive'),

**Comment by crezra** [comment]
Hi 

Indeed paths are passed query parameters to the tool

Closing this as working as intended
